---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.glusterfs default variables [[[
# ======================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst

# Gluster client configuration [[[
# --------------------------------

# .. envvar:: glusterfs__daemon_port [[[
#
# Port on which Gluster server daemin is listening.
glusterfs__daemon_port: '24007'
                                                                           # ]]]
# .. envvar:: glusterfs__manage_port [[[
#
# Port used by the servers in a cluster for management.
glusterfs__manage_port: '24008'
                                                                           # ]]]
                                                                           # ]]]
# APT packages [[[
# ----------------

# .. envvar:: glusterfs__base_packages [[[
#
# List of minimal APT packages required for Gluster cluster to be deployed.
glusterfs__base_packages:
  - 'glusterfs-client'

                                                                           # ]]]
# .. envvar:: glusterfs__packages [[[
#
# List of APT packages required for Gluster cluster to be deployed.
glusterfs__packages: []

                                                                           # ]]]
                                                                           # ]]]
# Network configuration [[[
# -------------------------

# .. envvar:: glusterfs__allow [[[
#
# List of IP addresses and network CIDR that are allowed to access the cluster,
# which is applied to all hosts in the Ansible inventory.
glusterfs__allow: []

                                                                           # ]]]
# .. envvar:: glusterfs__group_allow [[[
#
# List of IP addresses and subnets that are allowed to access the cluster,
# which is applied to to hosts in a specific group of the Ansible inventory.
glusterfs__group_allow: []

                                                                           # ]]]
# .. envvar:: glusterfs__how_allow [[[
#
# List of IP addresses and subnets that are allowed to access the cluster,
# which is applied to a specific host in the Ansible inventory.
glusterfs__host_allow: []

                                                                           # ]]]
# .. envvar:: glusterfs__dependent_allow [[[
#
# List of IP addresses and subnets that are allowed to access the cluster that
# is provided by another Ansible role.
glusterfs__dependent_allow: []

                                                                           # ]]]
# .. envvar:: glusterfs__combined_allow [[[
#
# List of combined IP addresses and subnets that are allowed to access the
# cluster.
glusterfs__combined_allow: '{{ glusterfs__allow
                                    + glusterfs__group_allow
                                    + glusterfs__host_allow
                                    + glusterfs__dependent_allow }}'

                                                                           # ]]]
                                                                           # ]]]
# SSL/TLS configuration [[[
# -------------------------

# .. envvar:: glusterfs__manage_tls_disabled [[[
#
# This disables encryption of management path.
glusterfs__manage_tls_disabled: False

                                                                           # ]]]
# .. envvar:: glusterfs__pki_realm [[[
#
# The name of the PKI realm, defaulted to the Ansible fully qualified hostname.
glusterfs__pki_realm: '{{ ansible_local.pki.realm
                                 if (ansible_local|d() and ansible_local.pki|d() and
                                     ansible_local.pki.realm|d())
                                 else "domain" }}'

                                                                           # ]]]
                                                                           # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: glusterfs__gluster_org__dependent_packages [[[
#
# Configuration for the :ref:`debops.gluster_org` Ansible role.
glusterfs__gluster_org__dependent_packages:
  - '{{ glusterfs__base_packages }}'
  - '{{ glusterfs__packages }}'

                                                                           # ]]]
                                                                           # ]]]
                                                                           # ]]]
