---

dependencies: []

galaxy_info:

  role_name: 'gluster_org'
  author: 'Julien Peeters'
  description: 'Configure Gluster APT repositories'
  company: 'Monkey Codex SAS'
  license: 'GPL-3.0'
  min_ansible_version: '2.5.0'
  platforms:
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - storage
    - sds
    - gluster
    - glusterfs
